### ISSUE TITLE
Spotify Ads

### ISSUE THREAD

**Issue by Qonrad** [nathanaccidentally/SystemHostBlocker#5]
Ads definitely still come up in Spotify. Even after removing & reinstalling, respringing/rebooting, and running iCleaner. I am on the latest version of Spotify. My device is a 6+ on 9.3.3. I am also using BdaySpotify2, Anywhere!, and a flex tweak that could be modifying the app, but I feel like hosts blocking should precede all of that.

**Comment by nathanaccidentally** [comment]
Thanks for opening an issue here. I will push a little experimental build to the latest [pull request](https://github.com/nathanaccidentally/SystemHostsBlocker/pull/4) later tonight with experimental Spotify blocking. In the first version I had blocking for Spotify ads but it was breaking Spotify for some people so I removed it.

**Edit:**

Ok I added experimental Spotify ad Blocking to the branch v1.3.1-beta. You can compile the deb yourself or wait a while until I get time. I'm at school now.
