### ISSUE TITLE
Spotify 

### ISSUE THREAD

**Issue by Qonrad** [nathanaccidentally/SystemHostBlocker#6]
As you said, I put another request issue here. Here is my info from last time.

Ads definitely still come up in Spotify. Even after removing & reinstalling, respringing/rebooting, and running iCleaner. I am on the latest version of Spotify. My device is a 6+ on 9.3.3. I am also using BdaySpotify2, Anywhere!, and a flex tweak that could be modifying the app, but I feel like hosts blocking should precede all of that.

I am also using coolstar's stashing on 9.3.3, so maybe that could affect things?

Thanks for your continued work on this!

**Comment by nathanaccidentally** [comment]
Spotify is a tricky one; They really don't want their ads blocked. I'll see what I can do!
